---
- name: Add VLANs to device(s)
  hosts: leafs
  tasks:
    - name: Add VLAN 10
      arista.eos.eos_vlans:
        config:
          - vlan_id: 10
            name: DMZ
            state: active
          - vlan_id: 999
            name: GHOST
            state: active
        state: merged
